# Generated by Django 4.0.5 on 2022-06-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_comment_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(default='https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png'),
        ),
    ]
