# Generated by Django 4.0.5 on 2022-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(),
        ),
    ]
